BOOTSTRAP_VERSION=5.3.8

bootstrap:
	curl -s -o www/css/bootstrap-$(BOOTSTRAP_VERSION).min.css https://cdn.jsdelivr.net/npm/bootstrap@$(BOOTSTRAP_VERSION)/dist/css/bootstrap.min.css

golang_wasm:
	curl -s -o www/javascript/sfomuseum.golang.wasm.bundle.js https://raw.githubusercontent.com/sfomuseum/js-sfomuseum-golang-wasm/refs/heads/main/dist/sfomuseum.golang.wasm.bundle.js
